#!/usr/bin/env node
/**
 * Bundle the Agents panel into one self-contained HTML document.
 *
 * MCP Apps hand the host a *string* of HTML, which it loads into a sandboxed
 * iframe under `default-src 'none'` unless the resource declares domains. So
 * there is nothing to fetch and nowhere to fetch it from: no `<link>`, no
 * `<script src>`, no CDN. Script and style must be inline, and every import
 * resolved ahead of time.
 *
 * The result is inlined into dist/mcp.mjs, because that bundle is the only
 * artifact the hosts copy — see scripts/build-mcp.mjs and test/bundle.test.ts,
 * which runs the server from a temp directory with nothing beside it. A UI read
 * from disk at runtime would work in the repository and fail in every host.
 *
 * @see features/agent-inventory/views/app-client.mjs — the entry point.
 */
import { build } from "esbuild";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = join(ROOT, "features", "agent-inventory", "views", "app-client.mjs");

/** The generated module the MCP server imports. Committed; see moduleSource. */
export const APP_HTML_MODULE = join(ROOT, "dist", "app-html.mjs");

/**
 * Build the panel and return the finished HTML document.
 * @returns {Promise<string>}
 */
export async function buildAppHtml() {
	const result = await build({
		entryPoints: [ENTRY],
		bundle: true,
		write: false,
		format: "esm",
		platform: "browser",
		// The view runs in whatever Chromium the host embeds. Matching the Node
		// floor would downlevel for no one.
		target: "es2022",
		// Minified, unlike dist/mcp.mjs. That bundle is kept readable because it
		// is the server and shows up in stack traces. This one is ~730 KB of
		// vendored zod and MCP protocol code that no one will read either way,
		// and it is embedded as a *string literal* inside the server bundle —
		// so every byte is doubled by JSON escaping in a committed file.
		minify: true,
		legalComments: "none",
		outfile: join(ROOT, "dist", "app-client.js"),
	});

	const script = result.outputFiles[0]?.text ?? "";
	const { INVENTORY_STYLES } = await import("../features/agent-inventory/views/styles.mjs");

	return htmlDocument(INVENTORY_STYLES, script);
}

/**
 * The generated module's source text.
 *
 * Written to dist/ rather than features/ deliberately. It is a build artifact,
 * and two existing guards would reject it as source: `tsc` typechecks
 * everything under features/, and design-tokens.test.ts fails any shipped
 * source file containing a hex literal — which this necessarily does, since the
 * inlined stylesheet *is* the palette. dist/ is exempt from both.
 *
 * @param {string} html
 */
export function moduleSource(html) {
	return `// Generated by scripts/build-app.mjs. Do not edit.
// Source is features/agent-inventory/views/app-client.mjs and views/styles.mjs.
// Rebuild with: npm run build
//
// The Agents panel as one self-contained HTML document, served as the
// ui://security-canvas/agents resource. Inline by necessity: an MCP App runs
// in a sandboxed iframe under a restrictive CSP with no network access.

/** @type {string} */
export const AGENTS_APP_HTML = ${JSON.stringify(html)};
`;
}

/**
 * The HTML shell.
 *
 * Differs from the canvas shell in two ways that matter. There is no theme
 * toggle: the host owns the theme and the view follows `hostContext`, so a
 * second control would fight it. And the body grows with its content instead of
 * pinning to `100vh` — the panel is a card inside a conversation, not a window,
 * and a viewport-height layout inside an auto-resized iframe collapses.
 *
 * @param {string} css
 * @param {string} script
 */
function htmlDocument(css, script) {
	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Agents</title>
<style>
${css}

/* The host sizes the frame; the panel reports its own height via autoResize. */
html, body { height: auto; overflow: visible; }
body { background: transparent; }
.page { height: auto; }
</style>
</head>
<body>
<div class="page"><div id="main" aria-busy="true"></div></div>
<script type="module">
${script}
</script>
</body>
</html>`;
}

// Standalone use: `node scripts/build-app.mjs` writes the module. The normal
// path is `npm run build`, which generates it as part of the server bundle.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
	const { writeFile, mkdir } = await import("node:fs/promises");
	const html = await buildAppHtml();
	await mkdir(dirname(APP_HTML_MODULE), { recursive: true });
	await writeFile(APP_HTML_MODULE, moduleSource(html));
	process.stdout.write(`dist/app-html.mjs  ${(html.length / 1024).toFixed(0)} KB of HTML\n`);
}
