#!/usr/bin/env node
/**
 * Bundle the MCP server into one self-contained file.
 *
 * Every host that runs this server copies the repository and then runs it. None
 * of them reliably installs dependencies first:
 *
 *   - The Copilot app never runs `npm install`; a plugin install is a file copy.
 *   - Claude Code's CLI does run `npm ci --ignore-scripts` when the plugin root
 *     has a lockfile, but Cowork copies the plugin without that step, so
 *     mcp.mjs died on its first import of @modelcontextprotocol/sdk and
 *     registered no tools at all.
 *
 * A bundle removes the question. dist/mcp.mjs inlines the SDK and zod, so the
 * server starts anywhere Node 20 exists, with no node_modules and no install
 * step to skip. It is committed for the same reason: the hosts that need it are
 * exactly the hosts that will not build it.
 *
 * Only the MCP host is bundled. extension.mjs imports @github/copilot-sdk,
 * which the Copilot app injects at runtime rather than resolving from disk, and
 * the canvas already works there.
 */
import { build } from "esbuild";
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { APP_HTML_MODULE, buildAppHtml, moduleSource } from "./build-app.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUTFILE = join(ROOT, "dist", "mcp.mjs");

// --check rebuilds into memory and compares, instead of writing. The bundle is
// committed, so the failure mode this guards against is a source change landing
// without a rebuild: the repository would then ship a stale server that passes
// every test, because the tests run the source and the hosts run the bundle.
const checkOnly = process.argv.includes("--check");

const pkg = JSON.parse(await readFile(join(ROOT, "package.json"), "utf8"));

// The Agents panel is generated first and inlined into the server bundle, so
// one artifact carries both. Building it here rather than as a separate npm
// script is what makes `--check` cover it: a change to the panel's markup or
// styles now shows up as a stale dist/mcp.mjs, exactly like a change to a tool.
const appHtml = await buildAppHtml();
const appModule = moduleSource(appHtml);
if (!checkOnly) {
	await mkdir(join(ROOT, "dist"), { recursive: true });
	await writeFile(APP_HTML_MODULE, appModule);
}

const result = await build({
	entryPoints: [join(ROOT, "mcp.mjs")],
	...(checkOnly ? { write: false, outfile: OUTFILE } : { outfile: OUTFILE }),
	bundle: true,
	platform: "node",
	// The engines floor. Keeps esbuild from downlevelling syntax the runtime
	// already supports, and fails loudly if a dependency needs something newer.
	target: "node20",
	format: "esm",
	// Node builtins stay external: bundling them is meaningless and esbuild
	// would try to resolve "node:http" as a package.
	packages: "bundle",
	external: [],
	// Keep the bundle readable. It is committed, so it shows up in diffs and in
	// stack traces; a minified blob would make both useless, and the ~1MB saved
	// buys nothing for a process that starts once per session.
	minify: false,
	sourcemap: false,
	legalComments: "none",
	banner: {
		js:
			`// security-canvas ${pkg.version} — generated by scripts/build-mcp.mjs. Do not edit.\n` +
			"// Source of truth is mcp.mjs and the modules under features/ and platform/.\n" +
			"// Rebuild with: npm run build\n",
	},
	metafile: true,
});

const built = checkOnly ? result.outputFiles[0].text : null;

if (checkOnly) {
	// Check the panel first. esbuild resolves mcp.mjs's dynamic import of
	// dist/app-html.mjs from *disk*, so a stale panel produces a bundle that is
	// stale in the same way and the comparison below would pass. Without this,
	// a change to the Agents markup could ship unbuilt and unnoticed.
	let committedApp;
	try {
		committedApp = await readFile(APP_HTML_MODULE, "utf8");
	} catch {
		process.stderr.write("dist/app-html.mjs is missing. Run: npm run build\n");
		process.exit(1);
	}
	if (committedApp !== appModule) {
		process.stderr.write(
			"dist/app-html.mjs is stale — the Agents panel does not match the source it is built from.\n" +
				"Run: npm run build, and commit the result.\n",
		);
		process.exit(1);
	}

	let committed;
	try {
		committed = await readFile(OUTFILE, "utf8");
	} catch {
		process.stderr.write("dist/mcp.mjs is missing. Run: npm run build\n");
		process.exit(1);
	}
	if (committed !== built) {
		process.stderr.write(
			"dist/mcp.mjs is stale — the bundle does not match the source it is built from.\n" +
				"The hosts run the bundle, so this ships behaviour that no test covers.\n" +
				"Run: npm run build, and commit the result.\n",
		);
		process.exit(1);
	}
	process.stdout.write("dist/mcp.mjs is up to date\n");
	process.exit(0);
}

await mkdir(join(ROOT, "dist"), { recursive: true });

// The shebang has to survive for `bin` to work when installed from npm.
await chmod(OUTFILE, 0o755);

const bytes = (await readFile(OUTFILE)).byteLength;
const outputKey = Object.keys(result.metafile.outputs)[0];
const inputs = Object.keys(result.metafile.outputs[outputKey].inputs).length;

process.stdout.write(`dist/mcp.mjs  ${(bytes / 1024).toFixed(0)} KB  from ${inputs} modules\n`);

// Mark the generated artifacts so they collapse in diffs and do not skew
// language statistics — together they are ~1.7 MB of vendored dependency code
// and one inlined HTML document.
await writeFile(
	join(ROOT, "dist", ".gitattributes"),
	"mcp.mjs linguist-generated=true\napp-html.mjs linguist-generated=true\n",
);
